// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv5el3_1-VupqqL8NkNDD-4A19jPYjNog',
    appId: '1:142218865657:web:56b1af9f58f7bff63deb28',
    messagingSenderId: '142218865657',
    projectId: 'fir-esp-3a314',
    authDomain: 'fir-esp-3a314.firebaseapp.com',
    databaseURL: 'https://fir-esp-3a314-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp-3a314.appspot.com',
    measurementId: 'G-W8NJ7F33FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQlQbiSq_76gQO9ZXZzIUjEGNJ2wbhUE',
    appId: '1:142218865657:android:786151dcf539b56e3deb28',
    messagingSenderId: '142218865657',
    projectId: 'fir-esp-3a314',
    databaseURL: 'https://fir-esp-3a314-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp-3a314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4_K2ZMn4IsAmK82RqV5X9JOOYxoLvRs',
    appId: '1:142218865657:ios:8d716f461b6588f03deb28',
    messagingSenderId: '142218865657',
    projectId: 'fir-esp-3a314',
    databaseURL: 'https://fir-esp-3a314-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp-3a314.appspot.com',
    iosBundleId: 'com.example.flutter5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4_K2ZMn4IsAmK82RqV5X9JOOYxoLvRs',
    appId: '1:142218865657:ios:8d716f461b6588f03deb28',
    messagingSenderId: '142218865657',
    projectId: 'fir-esp-3a314',
    databaseURL: 'https://fir-esp-3a314-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp-3a314.appspot.com',
    iosBundleId: 'com.example.flutter5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv5el3_1-VupqqL8NkNDD-4A19jPYjNog',
    appId: '1:142218865657:web:c3158210875f113c3deb28',
    messagingSenderId: '142218865657',
    projectId: 'fir-esp-3a314',
    authDomain: 'fir-esp-3a314.firebaseapp.com',
    databaseURL: 'https://fir-esp-3a314-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp-3a314.appspot.com',
    measurementId: 'G-JE30FB1TV8',
  );
}
